// feed/fyers_index_map.hpp -- GENERATED from the official FYERS Python SDK
// (fyers-apiv3 3.1.18, MIT licence), FyersWebsocket/map.json. Do not edit by
// hand: regenerate from a newer SDK release when FYERS adds an index.
//
// The data socket names an index topic by its exchange display name
// ("if|nse_cm|Nifty 50"), not by the numeric token the symbol-token API
// returns, so the socket client needs this table to subscribe to any index.
#pragma once

#include <array>
#include <string_view>

namespace altair::fyers_hsm {

struct SegmentName { std::string_view prefix; std::string_view segment; };

/// The first four digits of a FYERS fytoken select the socket segment.
inline constexpr std::array<SegmentName, 8> kSegments{{
    {"1010", "nse_cm"},
    {"1011", "nse_fo"},
    {"1120", "mcx_fo"},
    {"1210", "bse_cm"},
    {"1012", "cde_fo"},
    {"1211", "bse_fo"},
    {"1212", "bcs_fo"},
    {"1020", "nse_com"},
}};

struct IndexName { std::string_view symbol; std::string_view exchange_name; };

/// Sorted by `symbol` so lookup is a binary search.
inline constexpr std::array<IndexName, 175> kIndexNames{{
    {"BSE:100-INDEX", "BSE100"},
    {"BSE:100LARGECAPTMC-INDEX", "LCTMCI"},
    {"BSE:150MIDCAP-INDEX", "MID150"},
    {"BSE:200-INDEX", "BSE200"},
    {"BSE:250LARGEMIDCAP-INDEX", "LMI250"},
    {"BSE:250SMALLCAP-INDEX", "SML250"},
    {"BSE:400MIDSMALLCAP-INDEX", "MSL400"},
    {"BSE:500-INDEX", "BSE500"},
    {"BSE:ALLCAP-INDEX", "ALLCAP"},
    {"BSE:AUTO-INDEX", "AUTO"},
    {"BSE:BANKEX-INDEX", "BANKEX"},
    {"BSE:BASMTR-INDEX", "BASMTR"},
    {"BSE:BHRT22-INDEX", "BHRT22"},
    {"BSE:CARBONEX-INDEX", "CARBON"},
    {"BSE:CD-INDEX", "BSE CD"},
    {"BSE:CDGS-INDEX", "CDGS"},
    {"BSE:CG-INDEX", "BSE CG"},
    {"BSE:CPSE-INDEX", "CPSE"},
    {"BSE:DFRG-INDEX", "DFRGRI"},
    {"BSE:DIVIDENDSTABILITY-INDEX", "BSEDSI"},
    {"BSE:ENERGY-INDEX", "ENERGY"},
    {"BSE:ENHANCEDVALUE-INDEX", "BSEEVI"},
    {"BSE:ESG100-INDEX", "ESG100"},
    {"BSE:FIN-INDEX", "FIN"},
    {"BSE:FMC-INDEX", "BSEFMC"},
    {"BSE:GREENEX-INDEX", "GREENX"},
    {"BSE:HC-INDEX", "BSE HC"},
    {"BSE:INDIAMANUFACTURING-INDEX", "MFG"},
    {"BSE:INDSTR-INDEX", "INDSTR"},
    {"BSE:INFRA-INDEX", "INFRA"},
    {"BSE:IPO-INDEX", "BSEIPO"},
    {"BSE:IT-INDEX", "BSE IT"},
    {"BSE:LOWVOLATILITY-INDEX", "BSELVI"},
    {"BSE:LRGCAP-INDEX", "LRGCAP"},
    {"BSE:METAL-INDEX", "METAL"},
    {"BSE:MIDCAP-INDEX", "MIDCAP"},
    {"BSE:MIDSEL-INDEX", "MIDSEL"},
    {"BSE:MOMENTUM-INDEX", "BSEMOI"},
    {"BSE:OILGAS-INDEX", "OILGAS"},
    {"BSE:POWER-INDEX", "POWER"},
    {"BSE:PRIVATEBANKS-INDEX", "BSEPBI"},
    {"BSE:PSU-INDEX", "BSEPSU"},
    {"BSE:QUALITY-INDEX", "BSEQUI"},
    {"BSE:REALTY-INDEX", "REALTY"},
    {"BSE:SENSEX-INDEX", "SENSEX"},
    {"BSE:SME IPO-INDEX", "SMEIPO"},
    {"BSE:SMLCAP-INDEX", "SMLCAP"},
    {"BSE:SMLSEL-INDEX", "SMLSEL"},
    {"BSE:SNSX50-INDEX", "SNSX50"},
    {"BSE:SNXT50-INDEX", "SNXT50"},
    {"BSE:TECK-INDEX", "TECK"},
    {"BSE:TELCOM-INDEX", "TELCOM"},
    {"BSE:UTILS-INDEX", "UTILS"},
    {"NSE:BHARATBOND-APR30-INDEX", "BHARATBOND-APR30"},
    {"NSE:BHARATBOND-APR31-INDEX", "BHARATBOND-APR31"},
    {"NSE:BHARATBOND-APR32-INDEX", "BHARATBOND-APR32"},
    {"NSE:BHARATBOND-APR33-INDEX", "BHARATBOND-APR33"},
    {"NSE:FINNIFTY-INDEX", "Nifty Fin Service"},
    {"NSE:HANGSENG BEES-NAV-INDEX", "HangSeng BeES-NAV"},
    {"NSE:INDIAVIX-INDEX", "India VIX"},
    {"NSE:MIDCPNIFTY-INDEX", "NIFTY MID SELECT"},
    {"NSE:NIFTY100 EQL WGT-INDEX", "NIFTY100 EQL Wgt"},
    {"NSE:NIFTY100 LOWVOL30-INDEX", "NIFTY100 LowVol30"},
    {"NSE:NIFTY100-INDEX", "Nifty 100"},
    {"NSE:NIFTY100ALPHA30-INDEX", "Nifty100 Alpha 30"},
    {"NSE:NIFTY100ENHESG-INDEX", "Nifty100 Enh ESG"},
    {"NSE:NIFTY100ESG-INDEX", "NIFTY100 ESG"},
    {"NSE:NIFTY100ESGSECLDR-INDEX", "Nifty100ESGSecLdr"},
    {"NSE:NIFTY100LIQ15-INDEX", "Nifty100 Liq 15"},
    {"NSE:NIFTY200-INDEX", "Nifty 200"},
    {"NSE:NIFTY200MOMENTM30-INDEX", "Nifty200Momentm30"},
    {"NSE:NIFTY200QUALTY30-INDEX", "NIFTY200 QUALTY30"},
    {"NSE:NIFTY200VALUE30-INDEX", "Nifty200 Value 30"},
    {"NSE:NIFTY50 EQL WGT-INDEX", "NIFTY50 EQL Wgt"},
    {"NSE:NIFTY50-INDEX", "Nifty 50"},
    {"NSE:NIFTY500-INDEX", "Nifty 500"},
    {"NSE:NIFTY500EW-INDEX", "Nifty500 EW"},
    {"NSE:NIFTY500LMSEQL-INDEX", "Nifty500 LMS Eql"},
    {"NSE:NIFTY500LOWVOL50-INDEX", "Nifty500 LowVol50"},
    {"NSE:NIFTY500MOMENTM50-INDEX", "Nifty500Momentm50"},
    {"NSE:NIFTY500MULTICAP-INDEX", "NIFTY500 MULTICAP"},
    {"NSE:NIFTY500QLTY50-INDEX", "Nifty500 Qlty50"},
    {"NSE:NIFTY500SHARIAH-INDEX", "Nifty500 Shariah"},
    {"NSE:NIFTY500VALUE50-INDEX", "Nifty500 Value 50"},
    {"NSE:NIFTY50DIVPOINT-INDEX", "Nifty50 Div Point"},
    {"NSE:NIFTY50PR1XINV-INDEX", "Nifty50 PR 1x Inv"},
    {"NSE:NIFTY50PR2XLEV-INDEX", "Nifty50 PR 2x Lev"},
    {"NSE:NIFTY50SHARIAH-INDEX", "Nifty50 Shariah"},
    {"NSE:NIFTY50TR1XINV-INDEX", "Nifty50 TR 1x Inv"},
    {"NSE:NIFTY50TR2XLEV-INDEX", "Nifty50 TR 2x Lev"},
    {"NSE:NIFTY50VALUE20-INDEX", "Nifty50 Value 20"},
    {"NSE:NIFTYALPHA50-INDEX", "NIFTY Alpha 50"},
    {"NSE:NIFTYALPHALOWVOL-INDEX", "NIFTY AlphaLowVol"},
    {"NSE:NIFTYAQL30-INDEX", "Nifty AQL 30"},
    {"NSE:NIFTYAQLV30-INDEX", "Nifty AQLV 30"},
    {"NSE:NIFTYAUTO-INDEX", "Nifty Auto"},
    {"NSE:NIFTYBANK-INDEX", "Nifty Bank"},
    {"NSE:NIFTYCAPITALMKT-INDEX", "Nifty Capital Mkt"},
    {"NSE:NIFTYCOMMODITIES-INDEX", "Nifty Commodities"},
    {"NSE:NIFTYCONSRDURBL-INDEX", "NIFTY CONSR DURBL"},
    {"NSE:NIFTYCONSUMPTION-INDEX", "Nifty Consumption"},
    {"NSE:NIFTYCOREHOUSING-INDEX", "Nifty CoreHousing"},
    {"NSE:NIFTYCORPMAATR-INDEX", "Nifty Corp MAATR"},
    {"NSE:NIFTYCPSE-INDEX", "Nifty CPSE"},
    {"NSE:NIFTYDIVOPPS50-INDEX", "Nifty Div Opps 50"},
    {"NSE:NIFTYENERGY-INDEX", "Nifty Energy"},
    {"NSE:NIFTYEV-INDEX", "Nifty EV"},
    {"NSE:NIFTYFINSEREXBNK-INDEX", "Nifty FinSerExBnk"},
    {"NSE:NIFTYFINSRV2550-INDEX", "Nifty FinSrv25 50"},
    {"NSE:NIFTYFMCG-INDEX", "Nifty FMCG"},
    {"NSE:NIFTYGROWSECT15-INDEX", "Nifty GrowSect 15"},
    {"NSE:NIFTYGS10YR-INDEX", "Nifty GS 10Yr"},
    {"NSE:NIFTYGS10YRCLN-INDEX", "Nifty GS 10Yr Cln"},
    {"NSE:NIFTYGS1115YR-INDEX", "Nifty GS 11 15Yr"},
    {"NSE:NIFTYGS15YRPLUS-INDEX", "Nifty GS 15YrPlus"},
    {"NSE:NIFTYGS48YR-INDEX", "Nifty GS 4 8Yr"},
    {"NSE:NIFTYGS813YR-INDEX", "Nifty GS 8 13Yr"},
    {"NSE:NIFTYGSCOMPSITE-INDEX", "Nifty GS Compsite"},
    {"NSE:NIFTYHEALTHCARE-INDEX", "NIFTY HEALTHCARE"},
    {"NSE:NIFTYHIGHBETA50-INDEX", "Nifty HighBeta 50"},
    {"NSE:NIFTYHOUSING-INDEX", "Nifty Housing"},
    {"NSE:NIFTYINDDEFENCE-INDEX", "Nifty Ind Defence"},
    {"NSE:NIFTYINDDIGITAL-INDEX", "NIFTY IND DIGITAL"},
    {"NSE:NIFTYINDIAMFG-INDEX", "NIFTY INDIA MFG"},
    {"NSE:NIFTYINDTOURISM-INDEX", "Nifty Ind Tourism"},
    {"NSE:NIFTYINFRA-INDEX", "Nifty Infra"},
    {"NSE:NIFTYIPO-INDEX", "Nifty IPO"},
    {"NSE:NIFTYIT-INDEX", "Nifty IT"},
    {"NSE:NIFTYLARGEMID250-INDEX", "NIFTY LARGEMID250"},
    {"NSE:NIFTYLOWVOL50-INDEX", "Nifty Low Vol 50"},
    {"NSE:NIFTYM150QLTY50-INDEX", "NIFTY M150 QLTY50"},
    {"NSE:NIFTYMEDIA-INDEX", "Nifty Media"},
    {"NSE:NIFTYMETAL-INDEX", "Nifty Metal"},
    {"NSE:NIFTYMICROCAP250-INDEX", "NIFTY MICROCAP250"},
    {"NSE:NIFTYMIDCAP100-INDEX", "NIFTY MIDCAP 100"},
    {"NSE:NIFTYMIDCAP150-INDEX", "NIFTY MIDCAP 150"},
    {"NSE:NIFTYMIDCAP50-INDEX", "Nifty Midcap 50"},
    {"NSE:NIFTYMIDLIQ15-INDEX", "Nifty Mid Liq 15"},
    {"NSE:NIFTYMIDSML400-INDEX", "NIFTY MIDSML 400"},
    {"NSE:NIFTYMIDSMLHLTH-INDEX", "Nifty MidSml Hlth"},
    {"NSE:NIFTYMNC-INDEX", "Nifty MNC"},
    {"NSE:NIFTYMOBILITY-INDEX", "Nifty Mobility"},
    {"NSE:NIFTYMS400MQ100-INDEX", "NiftyMS400 MQ 100"},
    {"NSE:NIFTYMSFINSERV-INDEX", "Nifty MS Fin Serv"},
    {"NSE:NIFTYMSINDCONS-INDEX", "Nifty MS Ind Cons"},
    {"NSE:NIFTYMSITTELCM-INDEX", "Nifty MS IT Telcm"},
    {"NSE:NIFTYMULTIINFRA-INDEX", "Nifty Multi Infra"},
    {"NSE:NIFTYMULTIMFG-INDEX", "Nifty Multi Mfg"},
    {"NSE:NIFTYMULTIMQ50-INDEX", "Nifty Multi MQ 50"},
    {"NSE:NIFTYNEWCONSUMP-INDEX", "Nifty New Consump"},
    {"NSE:NIFTYNEXT50-INDEX", "Nifty Next 50"},
    {"NSE:NIFTYNONCYCCONS-INDEX", "Nifty NonCyc Cons"},
    {"NSE:NIFTYNXT50-INDEX", "Nifty Next 50"},
    {"NSE:NIFTYOILANDGAS-INDEX", "NIFTY OIL AND GAS"},
    {"NSE:NIFTYPHARMA-INDEX", "Nifty Pharma"},
    {"NSE:NIFTYPSE-INDEX", "Nifty PSE"},
    {"NSE:NIFTYPSUBANK-INDEX", "Nifty PSU Bank"},
    {"NSE:NIFTYPVTBANK-INDEX", "Nifty Pvt Bank"},
    {"NSE:NIFTYQLTYLV30-INDEX", "Nifty Qlty LV 30"},
    {"NSE:NIFTYQUALITY30-INDEX", "NIFTY100 Qualty30"},
    {"NSE:NIFTYREALTY-INDEX", "Nifty Realty"},
    {"NSE:NIFTYRURAL-INDEX", "Nifty Rural"},
    {"NSE:NIFTYSERVSECTOR-INDEX", "Nifty Serv Sector"},
    {"NSE:NIFTYSHARIAH25-INDEX", "Nifty Shariah 25"},
    {"NSE:NIFTYSML250MQ100-INDEX", "NiftySml250MQ 100"},
    {"NSE:NIFTYSML250Q50-INDEX", "Nifty Sml250 Q50"},
    {"NSE:NIFTYSMLCAP100-INDEX", "NIFTY SMLCAP 100"},
    {"NSE:NIFTYSMLCAP250-INDEX", "NIFTY SMLCAP 250"},
    {"NSE:NIFTYSMLCAP50-INDEX", "NIFTY SMLCAP 50"},
    {"NSE:NIFTYTATA25CAP-INDEX", "Nifty Tata 25 Cap"},
    {"NSE:NIFTYTOP10EW-INDEX", "Nifty Top 10 EW"},
    {"NSE:NIFTYTOP15EW-INDEX", "Nifty Top 15 EW"},
    {"NSE:NIFTYTOP20EW-INDEX", "Nifty Top 20 EW"},
    {"NSE:NIFTYTOTALMKT-INDEX", "NIFTY TOTAL MKT"},
    {"NSE:NIFTYTRANSLOGIS-INDEX", "Nifty Trans Logis"},
}};

} // namespace altair::fyers_hsm
