# research/tools/feature_cards.py -- writes research/papers/index.md and registry.json from one list,
# so the two never disagree. Run from the repo root: python3 research/tools/feature_cards.py .
import json, sys
root = sys.argv[1]
DEMO = "band-fade demo, 27,095 trades, 2015-2026, 1 lot, synthetic Black-76 premiums at INDIA VIX"
cards = [
 # ---- pairs / statistical arbitrage -------------------------------------------------
 dict(group="Pairs and statistical arbitrage", id="gatev-2006-pairs",
  paper="Gatev, E., Goetzmann, W. N. & Rouwenhorst, K. G. (2006). Pairs Trading: Performance of a Relative-Value Arbitrage Rule. Review of Financial Studies 19(3), 797-827.",
  link="https://doi.org/10.1093/rfs/hhj020 (working paper: https://www.nber.org/papers/w7032)",
  claim="Pairs matched on a 12-month formation window and traded for the next 6 months when the normalised spread opens by 2 sd earn excess returns of up to 11 % a year.",
  claimed_on="US equities (CRSP), daily, 1962-2002; distance method; returns fall in later years.",
  inputs="daily closes of both legs", horizon="days to months",
  formula="formation window -> pair and spread sd; open at |spread| >= 2 sd, close when the spread crosses zero",
  assumptions="liquid shorting; costs low relative to the spread; the relationship persists out of sample. Profits shrank after 1990.",
  impl="prototyped: strategies/pairs_futures.hpp (walk-forward formation/trading windows, nothing estimated on a traded day)",
  status="unverified", edge_bps=None,
  ours="NIFTY-BANKNIFTY futures, 2000-2026: 8 of 107 windows cointegrated, 15 trades, 60 % won, gross Rs 54,789, net Rs 46,193 with UNVERIFIED expenses. Too few trades to call. The stock pairs wait for the FYERS fetch."),
 dict(group="Pairs and statistical arbitrage", id="engle-granger-1987-cointegration",
  paper="Engle, R. F. & Granger, C. W. J. (1987). Co-integration and Error Correction: Representation, Estimation, and Testing. Econometrica 55(2), 251-276.",
  link="https://doi.org/10.2307/1913236",
  claim="Two I(1) series are cointegrated when a linear combination is stationary; regress one on the other and test the residual for a unit root.",
  claimed_on="theory, with macro examples",
  inputs="two price series (logs)", horizon="any",
  formula="log A = alpha + beta log B + e; ADF on e against MacKinnon's residual-based critical values, not the ordinary ADF table",
  assumptions="one cointegrating vector; the regression's direction matters in small samples; breaks in the relationship invalidate it.",
  impl="prototyped: strategies/cointegration.hpp (engle_granger, eg_critical)",
  status="unverified", edge_bps=None,
  ours="A test, not a signal. Used to refuse a window: the pairs walk trades only windows that pass at 5 %."),
 dict(group="Pairs and statistical arbitrage", id="mackinnon-2010-critical-values",
  paper="MacKinnon, J. G. (2010). Critical Values for Cointegration Tests. Queen's Economics Department Working Paper 1227.",
  link="Queen's Economics Department Working Paper No. 1227 (updates MacKinnon 1991)",
  claim="Response-surface critical values for residual-based cointegration tests at any sample size.",
  claimed_on="simulation", inputs="sample size, number of variables, trend terms", horizon="n/a",
  formula="c(p, T) = b_inf + b1/T + b2/T^2 + b3/T^3",
  assumptions="the residual-based (Engle-Granger) test with the stated deterministic terms.",
  impl="prototyped: strategies/cointegration.hpp (eg_critical)", status="unverified", edge_bps=None,
  ours="Method. Two series, no trend; the test checks it is stricter than the plain ADF value at the same size, as it must be."),
 dict(group="Pairs and statistical arbitrage", id="johansen-1991-cointegration",
  paper="Johansen, S. (1991). Estimation and Hypothesis Testing of Cointegration Vectors in Gaussian Vector Autoregressive Models. Econometrica 59(6), 1551-1580.",
  link="https://doi.org/10.2307/2938278",
  claim="Maximum-likelihood test for the number of cointegrating vectors among n series, with no normalisation choice.",
  claimed_on="theory", inputs="n price series", horizon="any",
  formula="reduced-rank VECM; trace and max-eigenvalue statistics",
  assumptions="Gaussian VAR; enough data per parameter.",
  impl="none (two-leg pairs use Engle-Granger; Johansen is needed for baskets of 3+)", status="unverified", edge_bps=None,
  ours="Not implemented."),
 dict(group="Pairs and statistical arbitrage", id="vidyamurthy-2004-pairs",
  paper="Vidyamurthy, G. (2004). Pairs Trading: Quantitative Methods and Analysis. Wiley.",
  link="ISBN 978-0-471-46067-1",
  claim="Trade the cointegration residual, not the price ratio or a correlation; a high correlation is not cointegration.",
  claimed_on="practitioner text, US equities", inputs="two price series", horizon="days to weeks",
  formula="spread = log A - beta log B; enter and exit on the spread's z-score",
  assumptions="beta is stable over the trading window.",
  impl="prototyped: strategies/pairs_futures.hpp", status="unverified", edge_bps=None,
  ours="Our data shows why a fixed ratio cap fails: BANKNIFTY/NIFTY ran from 0.61 (2000) to 2.66 (2019-07-05) and stayed above 2.6 for 91 days (2019-03-26 to 2020-02-28). The '< 2.6 forever' hypothesis is rejected."),
 dict(group="Pairs and statistical arbitrage", id="elliott-2005-ou-spread",
  paper="Elliott, R. J., van der Hoek, J. & Malcolm, W. P. (2005). Pairs Trading. Quantitative Finance 5(3), 271-276.",
  link="https://doi.org/10.1080/14697680500149370",
  claim="Model the spread as a mean-reverting (Ornstein-Uhlenbeck) state observed with noise; the reversion speed sets how long a trade should take.",
  claimed_on="theory with simulated data", inputs="spread series", horizon="days",
  formula="dX = kappa (theta - X) dt + sigma dW; half-life = ln 2 / kappa",
  assumptions="constant kappa; Gaussian noise.",
  impl="prototyped: strategies/cointegration.hpp (half_life); strategies/pairs_futures.hpp (time stop at 2 half-lives, max half-life 30 days)",
  status="unverified", edge_bps=None, ours="Used as a filter and a time stop."),
 dict(group="Pairs and statistical arbitrage", id="avellaneda-lee-2010-statarb",
  paper="Avellaneda, M. & Lee, J.-H. (2010). Statistical Arbitrage in the US Equities Market. Quantitative Finance 10(7), 761-782.",
  link="https://doi.org/10.1080/14697680903124632",
  claim="Residuals of stocks against sector ETFs or PCA factors, modelled as OU, traded on an s-score, earned Sharpe ratios of about 1.4 (1997-2007), lower afterwards.",
  claimed_on="US equities, 1997-2007", inputs="stock and factor returns", horizon="days",
  formula="s = (X - m) / sigma_eq; open at |s| > 1.25, close at |s| < 0.5-0.75; keep only fast reversion (kappa > 252/30)",
  assumptions="factor model is stable; ETF hedges available; costs of about 10 bp round trip.",
  impl="prototyped: strategies/residual_reversion.hpp + app/resid_reversion_main.cpp (market + leave-one-out sector factor, OU s-score 1.25 / 0.5 / 0.75, kappa > 252/30); the pairs walk (strategies/pairs_futures.hpp) uses the same filter", status="unverified", edge_bps=None,
  ours="Engine validated on synthetic panels (reverting residuals pay, random-walk residuals do not, no look-ahead). The NIFTY 50 run waits for ops/fetch_universe.ps1; today's constituents backtested over the past carry survivorship bias."),
 dict(group="Pairs and statistical arbitrage", id="bertram-2010-optimal-thresholds",
  paper="Bertram, W. K. (2010). Analytic Solutions for Optimal Statistical Arbitrage Trading. Physica A 389(11), 2234-2243.",
  link="https://doi.org/10.1016/j.physa.2010.01.045",
  claim="For an OU spread with a fixed cost per trade, entry and exit levels that maximise expected return per unit time have a closed form.",
  claimed_on="theory", inputs="OU parameters, cost per trade", horizon="days",
  formula="maximise (exit - entry - cost) / E[cycle time]; first-passage times of the OU process",
  assumptions="known OU parameters; symmetric entry and exit.",
  impl="none", status="unverified", edge_bps=None, ours="Not implemented; the thresholds are fixed."),
 dict(group="Pairs and statistical arbitrage", id="krauss-2017-review",
  paper="Krauss, C. (2017). Statistical Arbitrage Pairs Trading Strategies: Review and Outlook. Journal of Economic Surveys 31(2), 513-545.",
  link="https://doi.org/10.1111/joes.12153",
  claim="Survey of the five families of pairs methods (distance, cointegration, time series, stochastic control, other); profits fall over time and after costs.",
  claimed_on="literature survey", inputs="-", horizon="-", formula="-",
  assumptions="-", impl="none (reference)", status="unverified", edge_bps=None,
  ours="Used to pick the cointegration family over distance."),
 dict(group="Pairs and statistical arbitrage", id="rad-low-faff-2016-pairs-methods",
  paper="Rad, H., Low, R. K. Y. & Faff, R. (2016). The Profitability of Pairs Trading Strategies: Distance, Cointegration and Copula Methods. Quantitative Finance 16(10), 1541-1558.",
  link="https://doi.org/10.1080/14697688.2016.1164337 (SSRN 2614233)",
  claim="Distance and cointegration pairs both earn positive excess returns after time-varying costs; cointegration holds up better in later years; copulas trade more steadily but earn less.",
  claimed_on="US equities, 1962-2014", inputs="daily closes", horizon="days to months",
  formula="distance, Engle-Granger and copula pair selection on the same formation/trading design",
  assumptions="US cost levels; liquid shorts.",
  impl="prototyped: strategies/pairs_futures.hpp (cointegration method only)", status="unverified", edge_bps=None, ours="See gatev-2006-pairs."),
 dict(group="Pairs and statistical arbitrage", id="do-faff-2010-pairs-decay",
  paper="Do, B. & Faff, R. (2010). Does Simple Pairs Trading Still Work? Financial Analysts Journal 66(4), 83-95.",
  link="https://doi.org/10.2469/faj.v66.n4.1",
  claim="Profits of simple pairs trading keep falling, but the strategy does well in long turbulent periods, including 2007-2009.",
  claimed_on="US equities, 1962-2009", inputs="daily closes", horizon="days to months",
  formula="Gatev distance method", assumptions="-",
  impl="none (reference)", status="unverified", edge_bps=None,
  ours="Expect few cointegrated windows in calm years. On NIFTY-BANKNIFTY only 8 of 107 windows qualified."),
 dict(group="Pairs and statistical arbitrage", id="sen-2022-india-pairs",
  paper="Sen, J. (2022). Designing Efficient Pair-Trading Strategies Using Cointegration for the Indian Stock Market. arXiv:2211.07080.",
  link="https://arxiv.org/abs/2211.07080",
  claim="Cointegrated pairs inside NSE sectors (formed 2018-2020) made money in 2021, auto and realty most; some IT pairs lost.",
  claimed_on="NSE stocks, 5 sectors, formed 2018-2020, traded 2021 (one year out of sample)",
  inputs="daily closes", horizon="days to months", formula="Engle-Granger within a sector; z-score bands",
  assumptions="one year out of sample; cash equities, not futures; costs are not the point of the paper.",
  impl="prototyped: strategies/pairs_futures.hpp; config/pairs.csv pairs stocks within a sector",
  status="unverified", edge_bps=None, ours="Stock pairs wait for ops/fetch_pairs.ps1."),
 # ---- volatility models behind the bands --------------------------------------------
 dict(group="Volatility models behind the bands", id="bollerslev-1986-garch",
  paper="Bollerslev, T. (1986). Generalized Autoregressive Conditional Heteroskedasticity. Journal of Econometrics 31(3), 307-327.",
  link="https://doi.org/10.1016/0304-4076(86)90063-1",
  claim="Today's variance is a weighted sum of a constant, yesterday's squared shock and yesterday's variance.",
  claimed_on="theory, with US inflation data", inputs="returns", horizon="one step ahead",
  formula="sigma2_t = omega + alpha r2_{t-1} + beta sigma2_{t-1}; alpha + beta < 1",
  assumptions="symmetric response to shocks; stationary parameters.",
  impl="prototyped: analytics/garch.hpp; models/band_curriculum.hpp ('GARCH(1,1)')", status="rejected", edge_bps=None,
  ours="As a band for fading touches: NIFTY 957 trades, 40.3 % won, -Rs 693 a trade net; BANKNIFTY 954, 45.0 %, -Rs 656 (" + DEMO + "). The band is not at fault: the fade rule loses with every band."),
 dict(group="Volatility models behind the bands", id="glosten-1993-gjr",
  paper="Glosten, L. R., Jagannathan, R. & Runkle, D. E. (1993). On the Relation between the Expected Value and the Volatility of the Nominal Excess Return on Stocks. Journal of Finance 48(5), 1779-1801.",
  link="https://doi.org/10.1111/j.1540-6261.1993.tb05128.x",
  claim="Negative shocks raise next-period variance more than positive ones (leverage effect).",
  claimed_on="US equity index, monthly", inputs="returns", horizon="one step ahead",
  formula="sigma2_t = omega + (alpha + gamma 1[r_{t-1} < 0]) r2_{t-1} + beta sigma2_{t-1}",
  assumptions="threshold at zero.", impl="prototyped: models/band_curriculum.hpp ('GJR-GARCH')", status="rejected", edge_bps=None,
  ours="Fade on GJR bands: NIFTY -Rs 674 a trade net, BANKNIFTY -Rs 685 (" + DEMO + ")."),
 dict(group="Volatility models behind the bands", id="nelson-1991-egarch",
  paper="Nelson, D. B. (1991). Conditional Heteroskedasticity in Asset Returns: A New Approach. Econometrica 59(2), 347-370.",
  link="https://doi.org/10.2307/2938260",
  claim="Model log variance, so no positivity constraints are needed, with an asymmetric response to the sign of the shock.",
  claimed_on="US equity index, daily", inputs="returns", horizon="one step ahead",
  formula="ln sigma2_t = omega + beta ln sigma2_{t-1} + alpha (|z| - E|z|) + gamma z",
  assumptions="stationary log variance.", impl="prototyped: models/band_curriculum.hpp ('EGARCH')", status="rejected", edge_bps=None,
  ours="Fade on EGARCH bands: NIFTY -Rs 657 a trade net, BANKNIFTY -Rs 690 (" + DEMO + ")."),
 dict(group="Volatility models behind the bands", id="hansen-lunde-2005-garch11",
  paper="Hansen, P. R. & Lunde, A. (2005). A Forecast Comparison of Volatility Models: Does Anything Beat a GARCH(1,1)? Journal of Applied Econometrics 20(7), 873-889.",
  link="https://doi.org/10.1002/jae.800",
  claim="Out of 330 volatility models, none forecasts exchange-rate variance significantly better than GARCH(1,1); for IBM stock, models with a leverage effect do better.",
  claimed_on="DM/USD and IBM, daily, about 250 days out of sample", inputs="returns, realised variance", horizon="one day",
  formula="superior predictive ability test across a model universe",
  assumptions="loss function choice; realised variance as the target.",
  impl="prototyped: models/band_curriculum.hpp (the band curriculum ranks 14 band models on coverage)", status="unverified", edge_bps=None,
  ours="In the fade demo the spread between the band models is small next to the loss every one of them makes."),
 dict(group="Volatility models behind the bands", id="corsi-2009-har-rv",
  paper="Corsi, F. (2009). A Simple Approximate Long-Memory Model of Realized Volatility. Journal of Financial Econometrics 7(2), 174-196.",
  link="https://doi.org/10.1093/jjfinec/nbp001 (SSRN 1365738)",
  claim="Realised volatility is forecast well by a regression on its own last day, last week and last month (HAR): three horizons of traders, long memory without a long-memory model.",
  claimed_on="USD/CHF, S&P 500 and T-bond futures, intraday, 1990s-2000s", inputs="intraday returns -> daily realised variance", horizon="1 day to 1 month",
  formula="RV(t+1..t+h) = b0 + bd RV_d + bw RV_w + bm RV_m (fitted here in logs, lognormal mean)",
  assumptions="variance components are stable; jumps not separated.",
  impl="prototyped: analytics/har_rv.hpp (walk-forward, no look-ahead; test_har_rv)", status="unverified", edge_bps=None,
  ours="21-session NIFTY realised vol: HAR RMSE 7.2 vol points against 8.1 for the trailing 22-day value; BANKNIFTY 9.0 against 9.8. As an entry filter for the short straddle it adds nothing over selling every month."),
 dict(group="Volatility models behind the bands", id="andersen-bollerslev-1997-intraday",
  paper="Andersen, T. G. & Bollerslev, T. (1997). Intraday Periodicity and Volatility Persistence in Financial Markets. Journal of Empirical Finance 4(2-3), 115-158.",
  link="https://doi.org/10.1016/S0927-5398(97)00004-2",
  claim="Intraday volatility has a strong U-shaped time-of-day pattern; filter it out before modelling persistence.",
  claimed_on="S&P 500 futures and DM/USD, 5-minute", inputs="intraday returns", horizon="intraday",
  formula="r_{t,n} = sigma_t s_n Z_{t,n}, with s_n the time-of-day factor",
  assumptions="the pattern is stable across days.", impl="prototyped: models/band_curriculum.hpp ('Seasonal vol (time of day)')", status="rejected", edge_bps=None,
  ours="The least-bad band for fading on NIFTY: -Rs 562 a trade net; BANKNIFTY -Rs 607. Still a loss."),
 dict(group="Volatility models behind the bands", id="heston-1993-sv",
  paper="Heston, S. L. (1993). A Closed-Form Solution for Options with Stochastic Volatility. Review of Financial Studies 6(2), 327-343.",
  link="https://doi.org/10.1093/rfs/6.2.327",
  claim="Variance that mean-reverts as a square-root process gives closed-form option prices.",
  claimed_on="theory", inputs="returns or an option surface", horizon="any",
  formula="dv = kappa (theta - v) dt + xi sqrt(v) dW",
  assumptions="continuous paths; correlation between price and variance is constant.",
  impl="prototyped: models/band_curriculum.hpp ('Heston variance drift': the variance path only)", status="rejected", edge_bps=None,
  ours="Fade on Heston bands: NIFTY -Rs 684 a trade net, BANKNIFTY -Rs 691."),
 dict(group="Volatility models behind the bands", id="merton-1976-jumps",
  paper="Merton, R. C. (1976). Option Pricing When Underlying Stock Returns Are Discontinuous. Journal of Financial Economics 3(1-2), 125-144.",
  link="https://doi.org/10.1016/0304-405X(76)90022-2",
  claim="Adding Poisson jumps to diffusion fattens the tails that short-dated options price.",
  claimed_on="theory", inputs="returns", horizon="any",
  formula="dS/S = (mu - lambda k) dt + sigma dW + (J - 1) dN",
  assumptions="jumps are independent of the diffusion.", impl="prototyped: models/band_curriculum.hpp ('Jump diffusion (Merton)')", status="rejected", edge_bps=None,
  ours="Fade on jump-diffusion bands: NIFTY -Rs 594 a trade net, BANKNIFTY -Rs 740."),
 # ---- option selling ----------------------------------------------------------------
 dict(group="Option selling", id="black-1976-futures-options",
  paper="Black, F. (1976). The Pricing of Commodity Contracts. Journal of Financial Economics 3(1-2), 167-179.",
  link="https://doi.org/10.1016/0304-405X(76)90024-6",
  claim="Options on a forward are priced off the forward price, discounted at the risk-free rate.",
  claimed_on="theory", inputs="forward, strike, time, vol, rate", horizon="to expiry",
  formula="C = e^{-rT} [F N(d1) - K N(d2)], d1 = (ln F/K + sigma2 T / 2) / (sigma sqrt T)",
  assumptions="lognormal forward; one volatility for every strike (no skew).",
  impl="prototyped: analytics/greeks.hpp (black76); strategies/band_option_fade.hpp prices both legs with it",
  status="unverified", edge_bps=None,
  ours="Premiums in the demo are SYNTHETIC: Black-76 at INDIA VIX, flat across strikes. With no skew, out-of-the-money puts are priced too cheap and calls too dear relative to the market."),
 dict(group="Option selling", id="carr-wu-2009-vrp",
  paper="Carr, P. & Wu, L. (2009). Variance Risk Premiums. Review of Financial Studies 22(3), 1311-1341.",
  link="https://doi.org/10.1093/rfs/hhn038",
  claim="Implied variance (synthetic variance swap rates) exceeds realised variance on average, strongly for indices; the premium is not explained by standard risk factors.",
  claimed_on="5 US/EU indices and 35 stocks, 1996-2003", inputs="option chain, realised variance", horizon="30 days",
  formula="VRP = RV - SW (negative on average): sellers of variance earn it",
  assumptions="liquid strikes across the smile; the premium pays for crash risk.",
  impl="prototyped: strategies/vol_premium.hpp, app/vol_premium_main.cpp (synthetic VIX prices or NSE bhavcopy via app/bhavcopy.hpp)", status="unverified", edge_bps=None,
  ours="INDIA VIX was above NIFTY's next-21-session realised vol on 85.7 % of days, by 2.4 vol points on average (2015-2026). Selling the delta-hedged ATM monthly straddle every month at VIX-priced (SYNTHETIC) premiums nets Rs +6,295 a trade on NIFTY (t = 5.6, 136 trades) and Rs +10,366 on BANKNIFTY, UNVERIFIED expenses. Real ATM IV sits below VIX (VIX carries the put skew), so this overstates the premium: unproven until bhavcopy prices agree."),
 dict(group="Option selling", id="bakshi-kapadia-2003-delta-hedged",
  paper="Bakshi, G. & Kapadia, N. (2003). Delta-Hedged Gains and the Negative Market Volatility Risk Premium. Review of Financial Studies 16(2), 527-566.",
  link="https://doi.org/10.1093/rfs/16.2.0527",
  claim="Long delta-hedged index options lose money on average, more so at the money and when volatility is high: the volatility risk premium is negative.",
  claimed_on="S&P 500 options, 1988-1995", inputs="option prices, underlying", horizon="to expiry",
  formula="gain = C_T - C_0 - sum delta_t (S_{t+1} - S_t) - financing",
  assumptions="frequent delta hedging.",
  impl="prototyped: strategies/vol_premium.hpp (short straddle, futures delta hedge in whole lots, reset every close)", status="unverified", edge_bps=None,
  ours="The band fade is NOT delta-hedged and loses when the underlying keeps moving (see gao-2018). The hedged straddle in strategies/vol_premium.hpp roughly doubles the t-statistic of the same trade unhedged (NIFTY 4.5 vs 2.6, BANKNIFTY 5.2 vs 1.8, SYNTHETIC prices); in March 2020 the hedge earned back Rs 176,686 of a Rs 191,655 option loss."),
 dict(group="Option selling", id="coval-shumway-2001-option-returns",
  paper="Coval, J. D. & Shumway, T. (2001). Expected Option Returns. Journal of Finance 56(3), 983-1009.",
  link="https://doi.org/10.1111/0022-1082.00352",
  claim="Index calls earn less and puts far less than their betas imply; selling out-of-the-money puts and straddles earns a premium for crash risk.",
  claimed_on="S&P 500 index options, 1990-1995, weekly", inputs="option prices", horizon="a week to expiry",
  formula="mean weekly returns by strike; zero-beta straddle returns",
  assumptions="no crash in the sample window; margin is available.",
  impl="none", status="unverified", edge_bps=None, ours="Needs option-chain history."),
 dict(group="Option selling", id="gao-2018-intraday-momentum",
  paper="Gao, L., Han, Y., Li, S. Z. & Zhou, G. (2018). Market Intraday Momentum. Journal of Financial Economics 129(2), 394-414.",
  link="https://doi.org/10.1016/j.jfineco.2018.05.009",
  claim="The market's first half-hour return predicts its last half-hour return, more strongly on volatile days and high-volume days.",
  claimed_on="SPY and other US ETFs, 1993-2013", inputs="intraday returns", horizon="intraday",
  formula="r_last30 = a + b r_first30 + e, b > 0",
  assumptions="US ETFs; driven partly by late-day hedging and informed trading.",
  impl="none (the evidence is the band-fade demo)", status="unverified", edge_bps=None,
  ours="Consistent with our data: only 42.7 % (NIFTY) and 44.6 % (BANKNIFTY) of band touches close back inside the edge by 15:20. A touch is a breakout more often than a reversal, so fading it loses with every band model (-Rs 588 gross a trade on average). The paper's own regression is not yet run on NSE."),
]

# index.md
out = ["# Feature Card Index", "",
       "> One card per paper. `research/papers/registry.json` holds the same rows; both are written by",
       "> research/tools/feature_cards.py so they cannot disagree (edit the cards there). No PDFs are copied into the repo: each card links the published",
       "> version (DOI) or a public preprint. A paper's result is a fact about ITS market and period;",
       "> `status` is about ours. `rejected` means it failed on our data and STAYS here (the registry counts",
       "> attempts, not successes: research/feature_card.hpp).", "",
       "Expense figures quoted from the demos are UNVERIFIED until config/charges.toml is verified.", ""]
group = None
for c in cards:
    if c["group"] != group:
        group = c["group"]
        out += ["---", "", f"## {group}", ""]
    out += [f"### `{c['id']}`",
            f"- **Paper:** {c['paper']}",
            f"- **Link:** {c['link']}",
            f"- **Claim:** {c['claim']}",
            f"- **Claimed on:** {c['claimed_on']}",
            f"- **Inputs:** {c['inputs']}",
            f"- **Horizon:** {c['horizon']}",
            f"- **Formula:** `{c['formula']}`" if c['formula'] not in ('-', '') else "- **Formula:** -",
            f"- **Assumptions:** {c['assumptions']}",
            f"- **Impl:** `{c['impl']}`",
            f"- **Status:** `{c['status']}`",
            f"- **Edge (bps, post-cost):** {'—' if c['edge_bps'] is None else c['edge_bps']}",
            f"- **On our data:** {c['ours']}", ""]
open(f"{root}/research/papers/index.md", "w").write("\n".join(out).rstrip() + "\n")

reg = {"schema_version": 1, "updated": "2026-10-01",
       "papers": [{k: c[k] for k in ("id", "paper", "link", "claim", "claimed_on", "inputs", "horizon", "formula",
                                    "assumptions", "impl", "status", "edge_bps")} | {"our_result": c["ours"]} for c in cards]}
open(f"{root}/research/papers/registry.json", "w").write(json.dumps(reg, indent=2, ensure_ascii=False) + "\n")
print(len(cards), "cards")
